- name: "Install nginx"
  pacman:
    name: nginx-mainline
    state: present

- name: "Put nginx config"
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: "Start nginx daemon"
  systemd:
    name: nginx
    state: started
    enabled: yes
