- name: "Install python2-pyopenssl"
  pacman:
    name: python2-pyopenssl
    state: present

- name: "Generate OpenSSL private key"
  openssl_privatekey:
    path: /kurnevsky.net.pem
    size: 4096

- name: "Generate OpenSSL certificate signing request"
  openssl_csr:
    path: /kurnevsky.net.csr
    privatekey_path: /kurnevsky.net.pem
    country_name: BY
    email_address: kurnevsky@gmail.com
    common_name: kurnevsky.net

- name: "Generate a Self Signed OpenSSL certificate"
  openssl_certificate:
    path: /kurnevsky.net.crt
    privatekey_path: /kurnevsky.net.pem
    csr_path: /kurnevsky.net.csr
    provider: selfsigned

# - name: "Generate a Let's Encrypt Certificate"
#   openssl_certificate:
#     path: /etc/ssl/crt/ansible.com.crt
#     csr_path: /etc/ssl/csr/ansible.com.csr
#     provider: acme
#     acme_accountkey: /etc/ssl/private/ansible.com.pem
#     acme_challenge_path: /etc/ssl/challenges/ansible.com/
