- name: "Put iptables.rules"
  copy:
    src: files/iptables.rules
    dest: /etc/iptables/iptables.rules

- name: "Apply iptables rules"
  shell: iptables-restore /etc/iptables/iptables.rules 

- name: "Enable iptables loader"
  systemd:
    name: iptables
    state: started
    enabled: yes
