- name: "Accept input packets from localhost"
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: "Accept TCP input packets to SSH, HTTP, HTTPS, Tinc ports"
  iptables:
    chain: INPUT
    protocol: tcp
    match: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
  with_items: [ 22, 80, 443, 655 ]

- name: "Accept UDP input packets to Tinc port"
  iptables:
    chain: INPUT
    protocol: udp
    match: udp
    destination_port: 655
    jump: ACCEPT

- name: "Accept related/established TCP packets"
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: "Drop other TCP input packets"
  iptables:
    chain: INPUT
    jump: DROP
