[[ $TERM == 'dumb' ]] && unsetopt zle && PS1='$ ' && return

# History file
HISTFILE=~/.histfile
# The number of lines the shell will keep within one session
HISTSIZE=20480
# The number of lines of history will be saved
SAVEHIST=8192
PROMPT='[%n@%m %~]$ '
# Maximum input length for zsh-autosuggestions
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=10

# Remove all duplicates of current command from history, add current to end
setopt hist_ignore_all_dups
# Don't save any commands beginning with space
setopt hist_ignore_space
# Enable extended globs to interpret things like rm ^(file|file2)
setopt extended_glob
# Don't beep even if zsh don't like something
setopt no_beep
# Change directory even if user forgot to put 'cd' command in front, but entered path is valid
setopt auto_cd
# If possible, correct commands
setopt correct
# Append their history list to the history file, rather than replace it
setopt append_history
# If a pattern for filename generation has no matches, print an error, instead of leaving it unchanged in the argument list
setopt nomatch
# Report the status of background jobs immediately, rather than waiting until just before printing a prompt
setopt notify
# Allow parameter expansion, command substitution and arithmetic expansion for prompt string
setopt prompt_subst
# Remove any right prompt from display when accepting a command line
setopt transient_rprompt
# File completion after =
setopt magic_equal_subst
# Apply globbing to hidden files
setopt glob_dots

# Syntax highlighting
[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && \
  source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# Automatically search the official repositories through pkgfile, when entering an unrecognized command
[ -f /usr/share/doc/pkgfile/command-not-found.zsh ] && \
  source /usr/share/doc/pkgfile/command-not-found.zsh
# Autocomplete with history.
[ -f /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ] && \
  source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# Autocompletion with an arrow-key driven interface
zstyle ':completion:*' menu select
# Rehash automatically
zstyle ':completion:*' rehash true
# Sets autocompletion
autoload -Uz compinit && mkdir -p ~/.cache/zsh && compinit -d ~/.cache/zsh/zcompdump-$ZSH_VERSION
# Enable colors in prompt
autoload -Uz colors && colors
# Massive rename
autoload -Uz zmv
# Calculator
autoload -U zcalc

# Many programs change the terminal state, and often do not restore terminal settings on exiting abnormally
# This avoids the need to manually reset the terminal
ttyctl -f

# Find the key with: showkey -a
bindkey -e
[[ -n "${terminfo[khome]}" ]] && bindkey "${terminfo[khome]}" beginning-of-line
[[ -n "${terminfo[kend]}" ]] && bindkey "${terminfo[kend]}" end-of-line
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey "\e[3~" delete-char
bindkey '^ ' autosuggest-accept

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias zmv='noglob zmv -W'
aliases[=]='noglob zcalc -e'

export EDITOR=nano

if [[ $- == *i* ]] && [[ -z "$TMUX" ]] && [[ -n "$SSH_CONNECTION" ]]; then
  tmux attach-session -t ssh_tmux || tmux new-session -s ssh_tmux
  exit 0
fi
