- name: "Create locale.conf"
  copy:
    dest: /etc/locale.conf
    content: |
      LANG=en_US.UTF-8

- name: "Ensure a locale exists"
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: "Enable pacman options"
  lineinfile:
    path: /etc/pacman.conf
    regexp: '^\s*#?\s*{{ item }}$'
    line: '{{ item }}'
  with_items:
    - Color
    - VerbosePkgLists

- name: "Install helpful tools"
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - sudo
    - cronie
    - zsh
    - zsh-autosuggestions
    - zsh-syntax-highlighting
    - mc
    - p7zip

- name: "Install ansible utils"
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - python2-psycopg2
    - python2-pyopenssl

- name: "Add authorized key for root"
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: "Put zshrc to root home"
  copy:
    src: files/zshrc
    dest: /root/.zshrc

- name: "Change root shell to zsh"
  user:
    name: root
    shell: /bin/zsh

- name: "Start cronie daemon"
  systemd:
    name: cronie
    state: started
    enabled: yes
