- name: "Create locale.conf"
  copy:
    dest: /etc/locale.conf
    content: |
      LANG=en_US.UTF-8

- name: "Ensure a locale exists"
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: "Enable pacman options"
  lineinfile:
    path: /etc/pacman.conf
    regexp: '^\s*#?\s*{{ item }}$'
    line: '{{ item }}'
  with_items:
    - Color
    - VerbosePkgLists

- name: "Set logs size limit"
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^\s*#?\s*SystemMaxUse='
    line: 'SystemMaxUse=512M'

- name: "Install helpful tools"
  pacman:
    name:
      - sudo
      - cronie
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - mc
      - p7zip
      - lsof
      - tmux
    state: present

- name: "Install ansible utils"
  pacman:
    name:
      - python-psycopg2
      - python-pyopenssl
    state: present

- name: "Configure root user"
  user:
    name: root
    shell: /bin/zsh
    password: "{{ root_password | password_hash('sha512') }}"

- name: "Create general user"
  user:
    name: "{{ user_name }}"
    shell: /bin/zsh
    password: "{{ user_password | password_hash('sha512') }}"

- name: "Put zshrc to home"
  copy:
    src: files/zshrc
    dest: "~{{ item }}/.zshrc"
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items:
    - root
    - "{{ user_name }}"

- name: "Put tmux config to home"
  copy:
    src: files/.tmux.conf
    dest: "~{{ item }}/.tmux.conf"
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items:
    - root
    - "{{ user_name }}"

- name: "Create mc config directory"
  file:
    path: "~{{ item }}/.config/mc"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items:
    - root
    - "{{ user_name }}"

- name: "Put mc config to home"
  copy:
    src: "~/.config/mc/ini"
    dest: "~{{ item }}/.config/mc/ini"
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items:
    - root
    - "{{ user_name }}"

- name: "Add authorized key"
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
  with_items:
    - root
    - "{{ user_name }}"

- name: "Set ssh port 22"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^\s*#?\s*Port 22'
    line: 'Port 22'

- name: "Set ssh port 43683"
  lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: '^\s*#?\s*Port'
    line: 'Port 43683'

- name: "Set motd"
  copy:
    content: "Abandon all hope, ye who enter here.\n"
    dest: "/etc/motd"
    mode: 0644

- name: "Start cronie daemon"
  systemd:
    name: cronie
    state: started
    enabled: yes
