- name: "Create locale.conf"
  copy:
    dest: /etc/locale.conf
    content: |
      LANG=en_US.UTF-8

- name: "Ensure a locale exists"
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: "Install helpful tools"
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - cronie
    - zsh
    - mc
    - p7zip

- name: "Install ansible utils"
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - python2-psycopg2
    - python2-pyopenssl

- name: "Add authorized key for root"
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
