- name: "Install helpful tools"
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - cronie
    - zsh
    - mc
    - p7zip

- name: "Install ansible utils"
  pacman:
    name: python2-psycopg2
    state: present

- name: "Add authorized key for root"
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
