- name: "Install helpful tools"
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - zsh
    - mc
    - p7zip

- name: "Install ansible utils"
  pacman:
    name: python2-psycopg2
    state: present
