- name: "Install tor"
  pacman:
    name: tor
    state: present

- name: "Put tor config"
  template:
    src: templates/torrc.j2
    dest: /etc/tor/torrc

- name: "Put systemd service"
  template:
    src: templates/tor.service.j2
    dest: /etc/systemd/system/tor.service

- name: "Start tor daemon"
  systemd:
    name: tor
    state: started
    enabled: yes
