- name: "Install tor"
  pacman:
    name: tor
    state: present

- name: "Install anonymizing relay monitor"
  pacman:
    name: arm
    state: present

- name: "Put tor config"
  template:
    src: templates/torrc.j2
    dest: /etc/tor/torrc

- name: "Start tor daemon"
  systemd:
    name: tor
    state: started
    enabled: yes
