- hosts: servers
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: install python
      raw: pacman -S --needed --noconfirm python2
      changed_when: False

- hosts: servers
  become: true
  become_user: root
  roles:
    - role: util
      tags: ['util']
    - role: iptables
      tags: ['iptables']
    - role: tinc
      tags: ['tinc']
    - role: postgresql
      tags: ['postgresql']
    - role: tt-rss
      tags: ['tt-rss']
    - role: php-fpm
      tags: ['php-fpm']
    - role: nginx
      tags: ['nginx']
    - role: shadowsocks
      tags: ['shadowsocks']
