- hosts: servers
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: install python
      raw: pacman -S --needed --noconfirm python
      changed_when: False

- hosts: servers
  become: true
  become_user: root
  roles:
    - role: util
      tags: ['util']
    - role: iptables
      tags: ['iptables']
    - role: tc
      tags: ['tc']
    - role: tinc
      tags: ['tinc']
    - role: postgresql
      tags: ['postgresql']
    - role: tt-rss
      tags: ['tt-rss']
    - role: php-fpm
      tags: ['php-fpm']
    - role: nginx
      tags: ['nginx']
    - role: shadowsocks
      tags: ['shadowsocks']
    - role: tor
      tags: ['tor']
      when: tor_enabled
    - role: tox-node
      tags: ['tox-node']
      when: tox_enabled
    - role: iodine
      tags: ['iodine']
    - role: ptunnel
      tags: ['ptunnel']
