- name: "Install shadowsocks"
  pacman:
    name: shadowsocks-libev
    state: present

- name: "Install v2ray"
  pacman:
    name: shadowsocks-v2ray-plugin
    state: present

- name: "Create shadowsocks config directory"
  file:
    path: /etc/shadowsocks
    state: directory

- name: "Put shadowsocks config"
  template:
    src: templates/config.json.j2
    dest: /etc/shadowsocks/config.json

- name: "Start shadowsocks daemon"
  systemd:
    name: shadowsocks-libev-server@config
    state: started
    enabled: yes
