- name: "Install php-pgsql"
  pacman:
    name: php-pgsql
    state: present

- name: "Install tt-rss"
  pacman:
    name: tt-rss
    state: present

- name: "Add ttrss postgersql db"
  postgresql_db:
    name: ttrss
  register: postgres_db

- name: "Add ttrss postgersql user"
  postgresql_user:
    db: ttrss
    name: ttrss
    password: qwerty
    encrypted: yes

- name: "Create tt-rss db schema"
  shell: psql ttrss -U ttrss -f /usr/share/webapps/tt-rss/schema/ttrss_schema_pgsql.sql
  when: postgres_db.changed

- name: "Enable php extensions"
  lineinfile:
    path: /etc/php/php.ini
    regexp: '^\s*;?\s*extension={{ item }}$'
    line: 'extension={{ item }}'
  with_items:
    - curl
    - iconv
    - pgsql
    - soap

- name: "Put tt-rss config"
  copy:
    src: files/config.php
    dest: /etc/webapps/tt-rss/config.php

- name: "Put systemd service"
  copy:
    src: files/tt-rss.service
    dest: /etc/systemd/system/tt-rss.service

- name: "Start tt-rss sync daemon"
  systemd:
    name: tt-rss
    state: started
    enabled: yes

- name: "Add ttrss backup cron job"
  cron:
    name: "ttrss backup"
    hour: "*/4"
    job: "sudo -u postgres pg_dump ttrss | 7z a /ttrss.7z -mx3 -sittrss.sql"
