- name: "Put systemd service"
  template:
    src: templates/tc.service.j2
    dest: /etc/systemd/system/tc.service

- name: "Start tc service"
  systemd:
    name: tc
    state: started
    enabled: yes
